
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.56.1"

[dependencies.leo-ast]
path = "../ast"
version = "1.5.3"

[dependencies.leo-ast-passes]
path = "../ast-passes"
version = "1.5.3"

[dependencies.leo-errors]
path = "../../leo/errors"
version = "1.5.3"

[dependencies.leo-parser]
path = "../parser"
version = "1.5.3"

[dependencies.leo-span]
path = "../../leo/span"
version = "1.5.3"

[dependencies.sha2]
version = "0.10"

[features]
default = [ ]
ci_skip = [ "leo-ast/ci_skip" ]
